# Hello people!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: munteanuser blog <br><img src="http://previews.123rf.com/images/mandrixta/mandrixta1402/mandrixta140200009/26013588-Origami-flying-humming-bird-colibri-bird-on-a-whute-background-Stock-Photo.jpg" />
email: munteanuser@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This blog will be used for informing you about my opinion and different made solutions.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: munteanuser
github_username:  munteanuser

# Build settings
settings: _self_
